Rodrigofigari/VerDeVolver---PF

client/public/manifest.json
client/src/index.js

Se cambio el index y archivos del manicfest.json para poder renderizar.(Tiraba error)

Cambios en el index para renderizar

---

client/src/App.jsx
client/src/pages/EntitieDetail.jsx
client/src/pages/Entities.jsx

Pagina del detalle de la entidad.
-Imagen
-Input del monto a donar con el boton
-Nombre de la entidad
-Descripcion de la entidad
-Scroll con la recomendaciones
Falta crear el texto de las recomendaciones y el sistema de puntuacion

entitie detail page

---

client/src/pages/About.jsx

Pagina Quienes Somos?
-Titulo
-Descripcion del proyecto
-Cards con la foto, el nombre, links con las redes
Falta:
-Definir titulo y descripcion
-Poner los datos de todos
-Mejorar el estilo con el acabado final de la app

Feature about page

---

client/src/Components/DashboardRequest.jsx
client/src/Components/DashboardScroll.jsx
client/src/Components/TabListPosts.jsx
client/src/pages/Dashboard.jsx

Creacion de dashboard del admin con los componentes que utiliza (DashboardRequest, DashboardScroll, TabListPosts)

Dashboard admin page

---

client/src/Components/SearchBar.jsx
client/src/pages/Entities.jsx
client/src/pages/Home.jsx
client/src/redux/actions/entitiesActions.js
client/src/redux/reducers/entitiesReducer.js
client/src/redux/store.js

Sol redux searchbar-import in entities

---

client/src/App.jsx
client/src/Components/InforCardInput.jsx
client/src/Components/OverflowScroll.jsx
client/src/pages/EntityProfile.jsx
client/src/pages/Profile.jsx

Página de las entidades. DOnde pueden cambiar todos los datos necesarios

Entity profile

---

api/src/routes/donation/controllers.js
api/src/routes/donation/donations.js
api/src/routes/user/controllers.js
api/src/routes/user/usuario.js

Cris creación ruta para user terminada y funcionando

---

client/src/App.jsx
client/src/pages/SignUpEntities/SingUpEntitie.jsx
client/src/pages/SignUpEntities/validate.js
client/src/pages/SingUpEntitie.jsx

falta validation submit y modularizar el componente papiro

Sol validations be vd v

---

client/src/pages/SignUpEntities/SingUpEntitie.jsx
client/src/pages/SignUpEntities/validate.js
client/src/redux/actions/entitiesActions.js
client/src/redux/reducers/entitiesReducer.js

action-get-materials-en-el-form

---

client/src/Components/InforCardInput.jsx
client/src/Components/NavBar.jsx
client/src/Components/OverflowScroll.jsx
client/src/pages/EntitieDetail.jsx
client/src/pages/user profile/UserProfile.jsx

ahora el detalle recibe el id y busca los datos en la DB

Entity details

---

client/src/pages/About.jsx

centre texto quienes somos

---

api/index.js
api/src/routes/material/controllers.js
client/src/Components/AsideFilters.jsx
client/src/pages/Entities.jsx
client/src/pages/SignUpEntities/SingUpEntitie.jsx
client/src/pages/SignUpEntities/validate.js
client/src/redux/actions/entitiesActions.js
client/src/redux/reducers/entitiesReducer.js

Empecé la lógica del sort pero no funciona porque el raiting de la entity me viene en null y no logré entenderlo del todo en el back para modificarlo.

Fix form-filter-entities-by-material

---

api/src/routes/feedback/feedback.js
client/src/Components/AsideFilters.jsx
client/src/components/EntityCard.jsx
client/src/pages/Entities.jsx
client/src/redux/reducers/entitiesReducer.js

funciona el sort por rating y los filtros de entities

arreglados los filtros y funciona el sort

---

api/src/routes/VdV/vdv.js
api/src/services/createTransport.js
api/src/services/templateFormVdV.js

estamos modularizando el código que corresponde al uso de nodemailer en el back para no repetir tanto código y que quede más ordenado

Nodemailer dinamico

---

client/src/redux/actions/usersActions.js
client/src/redux/reducers/usersReducer.js

arreglando que la action envié el objeto de contacta para ser utilizada en el dashboard mas adelante

Cris implementación nodemailer front contactanos

---

client/src/pages/Home.jsx

Deploy sin carrusel - Directamente importamos libreria IG y pasamos div en el render

Deploy sin carrusel - Directamente importamos libreria IG y pasamos div en el render

---

client/src/Components/NavBar.jsx
client/src/pages/Home.jsx

Deploy sin carrusel - Importamos libreria de IG al home y renderizamos div directamente

Deploy sin carrusel - Importamos libreria de IG al home y renderizamos div directamente

---

api/src/routes/donation/controllers.js
client/src/pages/Home.jsx

Ruta de retorno del ususario MP cambiada para el deploy

Ruta de retorno del ususario MP cambiada para el deploy

---

api/src/routes/contact/controller.js

Queda configurada nueva password para contactanos en nodemailer

Arreglada nueva pssword para contactanos nodemailer

---

api/src/authentication/strategies/localStrategy.js
api/src/models/InstagramPosts.js
api/src/routes/index.js
api/src/routes/instagramPosts/controllers.js
api/src/routes/instagramPosts/instagramPosts.js
client/src/Components/PostsCarousel.jsx
client/src/Components/TabListPosts.jsx
client/src/pages/Home.jsx

modelos, rutas y controllers de posteos de instagram. funcion del admin en el dashboard para modificar los posteos existentes

modelos de posts y funciones del admin para modificarlos

---

api/src/routes/chargeDb/chargeDb.js
api/src/routes/user/controllers.js
api/src/routes/user/usuario.js

Creación de ruta para cambiar un usuario a owner

Cris creación role owner back

---

client/src/Components/AsideFilters.jsx
client/src/Components/RankingStars.jsx
client/src/components/EntityCard.jsx
client/src/pages/About.jsx
client/src/pages/Contact/Contact.jsx
client/src/pages/EntitieDetail.jsx
client/src/pages/Entities.jsx
client/src/pages/Home.jsx
client/src/pages/Map.jsx
client/src/pages/user profile/UserProfile.jsx
client/src/redux/actions/acountActions.js

en home y entity profile y formulario de entidad no lo implemente falta arreglar donaciones sin sesion iniciada

mantener sesion en todas las paginas

---

client/src/Components/DashboardRequest.jsx
client/src/Components/OverflowScroll.jsx
client/src/pages/Dashboard.jsx

el admin puede eliminar reseñas. También puede aceptar o denegar las solicitudes de entidades. Esto modifica el estado de la entidad a "activo" en caso de aprobado o sino la borra

Merjoras en el dashboard admin
